### ISSUE TITLE
Unable to build locally

### ISSUE THREAD

**Issue by davidhagg** [mikaeljorhult/segel#4]
Hello! Good job with this component! Looks promising.

I'm having some issues because I'm trying to have a different grid than the standard 24 h with 48 steps. Instead I would like 14 days, and have full days as the step size. This is causing some issues with the bookings being offset. 
![image](https://user-images.githubusercontent.com/1506085/64820452-b1797c00-d5b0-11e9-9eed-e3c2a7002edd.png)

I cloned the repo so I could debug it, but I cannot do ```npm run build```
I get:
```
TypeError: Cannot read property 'name' of undefined
```

**Comment by mikaeljorhult** [comment]
That's weird, the build process is running fine on macOS for me. Do you have additional stack trace for debugging?

**Comment by davidhagg** [comment]
Sure, I'm on PC. 

```
λ npm run build

> segel@0.1.4 build c:\dev\privat\segel
> vue-cli-service build --target lib --name segel ./src/index.js

 ERROR  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at entrypoint.getFiles.reduce (c:\dev\privat\segel\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:43:25)
    at Array.reduce (<anonymous>)
    at getEntrypointSize (c:\dev\privat\segel\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:40:27)
    at compiler.hooks.afterEmit.tap.compilation (c:\dev\privat\segel\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:75:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\dev\privat\segel\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (c:\dev\privat\segel\node_modules\tapable\lib\Hook.js:154:20)
    at asyncLib.forEachLimit.err (c:\dev\privat\segel\node_modules\webpack\lib\Compiler.js:482:27)
    at c:\dev\privat\segel\node_modules\neo-async\async.js:2818:7
    at done (c:\dev\privat\segel\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\dev\privat\segel\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (c:\dev\privat\segel\node_modules\webpack\lib\Compiler.js:464:33)
    at c:\dev\privat\segel\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! segel@0.1.4 build: `vue-cli-service build --target lib --name segel ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the segel@0.1.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by davidhagg** [comment]
Probably related to this: https://github.com/vuejs/vue-cli/issues/4572

**Comment by davidhagg** [comment]
I've explicitly added a dev-dependency to webpack ^4.40.2 and now the build works.

**Comment by mikaeljorhult** [comment]
Great that you found a solution!

I did a quick example of the use case you described and am not seeing the offset so please let me know if you're still seeing that issue.

```html
<div id='app'>
        <Segel
            v-bind:start="1567987200"
            v-bind:end="1569196800"
            v-bind:labels="labels"
            v-bind:steps="14"
            v-bind:resources="resources"
            v-bind:bookings="bookings"
            v-bind:editable="true"
            v-on:bookings-create="handleCreate"
            v-on:bookings-update="handleUpdate"
            v-on:bookings-delete="handleDelete"
        ></Segel>
    </div>

    <script>
        let app = new Vue({
          el: '#app',
          data: {
            resources: [
              {id: 11, name: 'Conference Room A'},
              {id: 12, name: 'Conference Room B'},
              {id: 13, name: 'Video Conference 1'},
              {id: 14, name: 'Video Conference 2'},
              {id: 15, name: 'Video Conference 3'}
            ],
            bookings: [],
            bookingID: 3,
            labels: [
              'mo', 'tu', 'we', 'th', 'fr', 'sa', 'su',
              'mo', 'tu', 'we', 'th', 'fr', 'sa', 'su',
            ],
          },
          methods: {
            /* SAME AS IN THE EXAMPLE IN THE README */
        });
    </script>
```

**Comment by davidhagg** [comment]
I think that had to do with my end date being one date too short. So my bad.
